# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: focal

language: r
cache: packages
sudo: required
repos:
  REPO_NAME: https://packagemanager.rstudio.com/all/__linux__/focal/latest

# https://github.com/edzer/sf_dep/blob/master/.travis.yml
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# pkgdown
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    all_branches: true
